// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class AndroidScanTempKtp
    {
        public int Serial { get; set; }
        public string Idnumber { get; set; }
        public string ArticleNumber { get; set; }
        public string DauTuan { get; set; }
        public int? SoLuong { get; set; }
        public string TenFile { get; set; }
        public string UserInsert { get; set; }
        public DateTime? NgayInsert { get; set; }
    }
}