// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class ArticleNumberProductGia
    {
        public int Serial { get; set; }
        public string ArticleNumber { get; set; }
        public double? Gia { get; set; }
        public DateTime? NgayBd { get; set; }
        public DateTime? NgayKt { get; set; }
        public string UserInsert { get; set; }
        public DateTime? NgayInsert { get; set; }
    }
}