// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class ArticleNumberProduct
    {
        public ArticleNumberProduct()
        {
            DonHangMua = new HashSet<DonHangMua>();
            KeHoachXuatHang = new HashSet<KeHoachXuatHang>();
            KhoTpInfoArt = new HashSet<KhoTpInfoArt>();
            KhoTpNk = new HashSet<KhoTpNk>();
        }

        public int Serial { get; set; }
        public string MaSp { get; set; }
        public string ArticleNumber { get; set; }
        public double? SoLuong { get; set; }
        public double? Gia { get; set; }
        public double? Slpallet { get; set; }
        public string TypeOther { get; set; }
        public string MaMau { get; set; }
        public string UserInsert { get; set; }
        public DateTime? NgayInsert { get; set; }

        public virtual MaMau MaMauNavigation { get; set; }
        public virtual SanPham MaSpNavigation { get; set; }
        public virtual ICollection<DonHangMua> DonHangMua { get; set; }
        public virtual ICollection<KeHoachXuatHang> KeHoachXuatHang { get; set; }
        public virtual ICollection<KhoTpInfoArt> KhoTpInfoArt { get; set; }
        public virtual ICollection<KhoTpNk> KhoTpNk { get; set; }
    }
}