// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class ChiTietKhuVuc
    {
        public int Stt { get; set; }
        public string MaSp { get; set; }
        public string MaCt { get; set; }
        public string MaCtLink { get; set; }
        public double? SlctQuyDoi { get; set; }
        public string KhuVuc { get; set; }
        public string ChonMot { get; set; }
        public string UserInsert { get; set; }

        public virtual SanPhamChiTiet MaCtNavigation { get; set; }
    }
}