// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class DataDropDownList
    {
        public int Serial { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public string TypeName { get; set; }
    }
}