// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class DeviceIdandroid
    {
        public int Serial { get; set; }
        public string DeviceId { get; set; }
        public string UserName { get; set; }
        public string DeviceName { get; set; }
        public DateTime? NgayInsert { get; set; }
    }
}