// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class DonHangMua
    {
        public int Serial { get; set; }
        public string MaHd { get; set; }
        public string ArticleNumber { get; set; }
        public string MaSp { get; set; }
        public string PhanLoai { get; set; }
        public double? SoLuong { get; set; }
        public double? Buffer { get; set; }
        public int? Mua { get; set; }
        public string GhiChu { get; set; }
        public DateTime? NgayInsert { get; set; }

        public virtual ArticleNumberProduct ArticleNumberNavigation { get; set; }
    }
}