// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class DonHangPiform
    {
        public DonHangPiform()
        {
            KeHoachJob = new HashSet<KeHoachJob>();
            KeHoachXuatHang = new HashSet<KeHoachXuatHang>();
        }

        public int Serial { get; set; }
        public string Ponumber { get; set; }
        public string DonHang { get; set; }
        public string MaKh { get; set; }
        public string MaNcc { get; set; }
        public string DiaChi { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string HanThanhToan { get; set; }
        public string ThoiGianGiao { get; set; }
        public string LoaiCont { get; set; }
        public string GhiChu { get; set; }
        public string NoiDen { get; set; }
        public DateTime? NgayNhanDonHang { get; set; }
        public DateTime? NgayKhyeuCau { get; set; }
        public string Forworder { get; set; }
        public DateTime? NgayDuKien { get; set; }
        public string DraftPi { get; set; }
        public string KhoHang { get; set; }
        public string UserInsert { get; set; }
        public DateTime? NgayInsert { get; set; }

        public virtual NhaCungCap MaNccNavigation { get; set; }
        public virtual ICollection<KeHoachJob> KeHoachJob { get; set; }
        public virtual ICollection<KeHoachXuatHang> KeHoachXuatHang { get; set; }
    }
}