// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class DonHangPisuaDoi
    {
        public int Serial { get; set; }
        public string Ponumber { get; set; }
        public DateTime? NgayKhyeuCau { get; set; }
        public DateTime? NgayKhyeuCauOld { get; set; }
        public string LyDo { get; set; }
        public string UserNhap { get; set; }
        public DateTime? NgayInsert { get; set; }
    }
}