// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class DonHangSoHd
    {
        public int Serial { get; set; }
        public string MaKh { get; set; }
        public string SoHd { get; set; }
        public int Mua { get; set; }
        public string UserInsert { get; set; }
        public DateTime? NgayInsert { get; set; }

        public virtual KhachHang MaKhNavigation { get; set; }
    }
}