// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class DonHangQckiem
    {
        public int Serial { get; set; }
        public string Ponumber { get; set; }
        public DateTime NgayKiem { get; set; }
        public string GhiChu { get; set; }
        public int KetQua { get; set; }
        public string NguoiKiem { get; set; }
        public string UserInsert { get; set; }
        public DateTime? NgayInsert { get; set; }
    }
}