// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class EmailList
    {
        public int Serial { get; set; }
        public string Email { get; set; }
        public string FullName { get; set; }
        public int Type { get; set; }
    }
}