// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class FileHoSo
    {
        public int Serial { get; set; }
        public string TableName { get; set; }
        public int? SerialLink { get; set; }
        public string TenFile { get; set; }
        public string UrlFile { get; set; }
        public string DienGiai { get; set; }
        public double? DungLuong { get; set; }
        public string Dvt { get; set; }
        public string UserInsert { get; set; }
        public DateTime? NgayInsert { get; set; }
    }
   
   
}