// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class Invoice
    {
        public Invoice()
        {
            InvoiceHoSo = new HashSet<InvoiceHoSo>();
            InvoiceItem = new HashSet<InvoiceItem>();
            InvoiceItemOther = new HashSet<InvoiceItemOther>();
        }

        public int Serial { get; set; }
        public string InvoiceNumber { get; set; }
        public string MaKh { get; set; }
        public DateTime? NgayTauChay { get; set; }
        public DateTime? NgayTauDen { get; set; }
        public DateTime? NgayNhanHang { get; set; }
        public DateTime? NgayHenTra { get; set; }
        public DateTime? NgayThanhToan { get; set; }
        public string NoiDen { get; set; }
        public string DiaChiDen { get; set; }
        public string GhiChu { get; set; }
        public string NguoiLienHe { get; set; }
        public double? ThanhToan { get; set; }
        public string Mbl { get; set; }
        public string Scaccode { get; set; }
        public string Cntr { get; set; }
        public string Vessel { get; set; }
        public string UserInsert { get; set; }
        public DateTime? NgayInsert { get; set; }

        public virtual KhachHang MaKhNavigation { get; set; }
        public virtual ICollection<InvoiceHoSo> InvoiceHoSo { get; set; }
        public virtual ICollection<InvoiceItem> InvoiceItem { get; set; }
        public virtual ICollection<InvoiceItemOther> InvoiceItemOther { get; set; }
    }
}