// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class InvoiceItem
    {
        public int Serial { get; set; }
        public int? SerialInvoice { get; set; }
        public string PonumberItem { get; set; }
        public string UserInsert { get; set; }
        public DateTime? NgayInsert { get; set; }

        public virtual Invoice SerialInvoiceNavigation { get; set; }
    }
}