// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class KeHoachNccchungTu
    {
        public KeHoachNccchungTu()
        {
            KeHoachNccitem = new HashSet<KeHoachNccitem>();
            KeHoachNccitemSp = new HashSet<KeHoachNccitemSp>();
        }

        public int Serial { get; set; }
        public int? Sttct { get; set; }
        public string MaChungTu { get; set; }
        public DateTime? Ngay { get; set; }
        public string MaNcc { get; set; }
        public string DienGiai { get; set; }
        public string Duyet { get; set; }
        public DateTime? NgayBd { get; set; }
        public DateTime? NgayKt { get; set; }
        public string LoaiHang { get; set; }
        public string UserInsert { get; set; }
        public DateTime? NgayInsert { get; set; }

        public virtual ICollection<KeHoachNccitem> KeHoachNccitem { get; set; }
        public virtual ICollection<KeHoachNccitemSp> KeHoachNccitemSp { get; set; }
    }
}