// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class KeHoachXuatHangDel
    {
        public int Serial { get; set; }
        public string KhachHang { get; set; }
        public string DonHang { get; set; }
        public string ArticleNumber { get; set; }
        public string TenSp { get; set; }
        public string KhoDuKien { get; set; }
        public string LoaiKhoDuKien { get; set; }
        public string QuocGia { get; set; }
        public string Conumber { get; set; }
        public DateTime? NgayKhyeuCau { get; set; }
        public DateTime? NgayNhanDonHang { get; set; }
        public string Transit { get; set; }
        public DateTime? NgayDuKien { get; set; }
        public int? MucDo { get; set; }
        public string NhaMay { get; set; }
        public string SoHd { get; set; }
        public double? SldonHang { get; set; }
        public double? SldaXuat { get; set; }
        public double? SldatHang { get; set; }
        public double? Slhuy { get; set; }
        public string KhoDen { get; set; }
        public string LoaiKhoDen { get; set; }
        public string CuaHangDen { get; set; }
        public string Ofnumber { get; set; }
        public string OfnumberReport { get; set; }
        public DateTime? NgayXuat { get; set; }
        public string GhiChu { get; set; }
        public string LoaiGo { get; set; }
        public string LoaiCont { get; set; }
        public int? DaXuat { get; set; }
        public string LenCont { get; set; }
        public string Type { get; set; }
        public string DaKiem { get; set; }
        public string DienGiai { get; set; }
        public DateTime? NgayInsert { get; set; }
        public DateTime? NgayInsertDel { get; set; }
        public DateTime? Etd { get; set; }
        public DateTime? Eta { get; set; }
        public DateTime? Booking { get; set; }
    }
}