// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class KeHoachJob
    {
        public KeHoachJob()
        {
            KeHoachNccitem = new HashSet<KeHoachNccitem>();
            KeHoachNccitemSp = new HashSet<KeHoachNccitemSp>();
        }

        public int Serial { get; set; }
        public string OfnumberReport { get; set; }
        public string ArticleNumber { get; set; }
        public int? Sttkh { get; set; }
        public string MaKeHoach { get; set; }
        public int? Slkh { get; set; }
        public DateTime? NgayBd { get; set; }
        public DateTime? NgayKt { get; set; }
        public string MaNcc { get; set; }
        public string LoaiHang { get; set; }
        public DateTime? NgayBdgh { get; set; }
        public DateTime? NgayKtgh { get; set; }
        public string ChuyenOs { get; set; }
        public string GhiChu { get; set; }
        public double? KhoTinhChe { get; set; }
        public double? KhoChoRap { get; set; }
        public double? KhoChoSon { get; set; }
        public double? GiaCong { get; set; }
        public string UserInsert { get; set; }
        public DateTime? NgayInsert { get; set; }

        public virtual DonHangPiform OfnumberReportNavigation { get; set; }
        public virtual ICollection<KeHoachNccitem> KeHoachNccitem { get; set; }
        public virtual ICollection<KeHoachNccitemSp> KeHoachNccitemSp { get; set; }
    }
}