// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class KeHoachNccitemSp
    {
        public int Serial { get; set; }
        public int? SerialCt { get; set; }
        public int? SerialLinkItem { get; set; }
        public string MaSp { get; set; }
        public string MaKeHoach { get; set; }
        public int? Slkh { get; set; }
        public string ArticleNumber { get; set; }
        public string KhuVuc { get; set; }

        public virtual KeHoachJob MaKeHoachNavigation { get; set; }
        public virtual KeHoachNccchungTu SerialCtNavigation { get; set; }
    }
}