// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class KeHoachNccitem
    {
        public KeHoachNccitem()
        {
            KhoChoRap = new HashSet<KhoChoRap>();
        }

        public int Serial { get; set; }
        public int? SerialCt { get; set; }
        public int? SerialLinkItem { get; set; }
        public string MaKeHoach { get; set; }
        public string MaSp { get; set; }
        public double? SoLuong { get; set; }
        public string Dvt { get; set; }
        public double? DonGia { get; set; }
        public DateTime? NgayBd { get; set; }
        public DateTime? NgayKt { get; set; }
        public string KhuVuc { get; set; }
        public string MaChiTiet { get; set; }
        public string DienGiai { get; set; }
        public double? Slnkcl { get; set; }
        public double? Slxkcl { get; set; }
        public string UserInsert { get; set; }
        public DateTime? NgayInsert { get; set; }

        public virtual KeHoachJob MaKeHoachNavigation { get; set; }
        public virtual KeHoachNccchungTu SerialCtNavigation { get; set; }
        public virtual ICollection<KhoChoRap> KhoChoRap { get; set; }
    }
}