// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class KhachHang
    {
        public KhachHang()
        {
            DonHangSoHd = new HashSet<DonHangSoHd>();
            Invoice = new HashSet<Invoice>();
            KhoTpChungTu = new HashSet<KhoTpChungTu>();
            SanPham = new HashSet<SanPham>();
        }

        public int Serial { get; set; }
        public string MaKh { get; set; }
        public string TenKh { get; set; }
        public string DiaChi { get; set; }
        public string TinhThanh { get; set; }
        public string QuocGia { get; set; }
        public string NguoiLh { get; set; }
        public string Email { get; set; }
        public string DienThoaiBan { get; set; }
        public string DiDong { get; set; }
        public string Website { get; set; }
        public string DaiDienPl { get; set; }
        public string SoFax { get; set; }
        public string SoTk { get; set; }
        public string TenNh { get; set; }
        public string MaSoThue { get; set; }
        public string LoaiHinhKinhDoanh { get; set; }
        public int? NoiBo { get; set; }
        public string UserInsert { get; set; }
        public string PathImg { get; set; }

        public virtual ICollection<DonHangSoHd> DonHangSoHd { get; set; }
        public virtual ICollection<Invoice> Invoice { get; set; }
        public virtual ICollection<KhoTpChungTu> KhoTpChungTu { get; set; }
        public virtual ICollection<SanPham> SanPham { get; set; }
    }
}