// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class KhachHangShipto
    {
        public int Stt { get; set; }
        public string MaKh { get; set; }
        public string TenKh { get; set; }
        public string ShipTo { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
    }
}