// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class KhoChoRap
    {
        public int Serial { get; set; }
        public int? ChungTu { get; set; }
        public int? SerialKeHoach { get; set; }
        public string NoiGiao { get; set; }
        public string NoiNhan { get; set; }
        public string MaCt { get; set; }
        public string MaKehoach { get; set; }
        public double? Slnhap { get; set; }
        public double? Slxuat { get; set; }
        public DateTime? Ngay { get; set; }
        public string GhiChu { get; set; }
        public string LyDo { get; set; }
        public string ChatLuong { get; set; }
        public string NhaMay { get; set; }
        public string UserNhap { get; set; }
        public int? SoPhieu { get; set; }
        public string ArticleNumber { get; set; }
        public string MauSp { get; set; }
        public string LoaiHang { get; set; }
        public DateTime? NgayInsert { get; set; }

        public virtual KeHoachNccitem SerialKeHoachNavigation { get; set; }
    }
}