// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class KhoTpNxnoiBo
    {
        public int Serial { get; set; }
        public string Idnumber { get; set; }
        public string KhachHang { get; set; }
        public string NoiNhan { get; set; }
        public int? Slnhap { get; set; }
        public int? Slxuat { get; set; }
        public DateTime? Ngay { get; set; }
        public DateTime? NgayInsert { get; set; }
        public string GhiChu { get; set; }
        public string UserNhap { get; set; }
    }
}