// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class KhoTpChuyenPoLog
    {
        public int Serial { get; set; }
        public string Idnumber { get; set; }
        public string PoOld { get; set; }
        public string PoNew { get; set; }
        public string UserInsert { get; set; }
        public string GhiChu { get; set; }
        public DateTime? NgayInsert { get; set; }
    }
}