// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class KhoTpTemPallet
    {
        public int Serial { get; set; }
        public string GhiChu { get; set; }
    }
}