// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class KhoTpInfoArt
    {
        public int Serial { get; set; }
        public string ArticleNumber { get; set; }
        public string ProductName { get; set; }
        public string ItemNo { get; set; }
        public double? PiecesOfPacked { get; set; }
        public double? Height { get; set; }
        public double? Width { get; set; }
        public double? Length { get; set; }
        public double? Grossweight { get; set; }
        public double? Netweight { get; set; }
        public double? Cbm { get; set; }
        public string Hscode { get; set; }
        public DateTime? DateBegin { get; set; }
        public DateTime? DateEnd { get; set; }

        public virtual ArticleNumberProduct ArticleNumberNavigation { get; set; }
    }
}