// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class KhoTpViTri
    {
        public int Serial { get; set; }
        public string Idnumber { get; set; }
        public string ViTri { get; set; }
        public string GroupPallet { get; set; }
        public string UserNhap { get; set; }
        public DateTime? NgayInsert { get; set; }

        public virtual KhoTpSoDo ViTriNavigation { get; set; }
    }
}