// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class KhoTpHclyDo
    {
        public int Serial { get; set; }
        public string MaSp { get; set; }
        public string ArticleNumber { get; set; }
        public string LyDo { get; set; }
        public double? Slhc { get; set; }
        public string SoBb { get; set; }
        public DateTime? NgayInsert { get; set; }
    }
}