// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class KhoTpXk
    {
        public int Serial { get; set; }
        public int? ChungTu { get; set; }
        public string Idnumber { get; set; }
        public DateTime? NgayInsert { get; set; }
        public string GhiChu { get; set; }

        public virtual KhoTpChungTu ChungTuNavigation { get; set; }
        public virtual KhoTpNk IdnumberNavigation { get; set; }
    }
}