// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class KhoTpScanItem
    {
        public int Serial { get; set; }
        public int SerialCt { get; set; }
        public string Idnumber { get; set; }
        public DateTime? NgayInsert { get; set; }

        public virtual KhoTpScanCt SerialCtNavigation { get; set; }
    }
}