// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class KhoTpChungTu
    {
        public KhoTpChungTu()
        {
            KhoTpNk = new HashSet<KhoTpNk>();
        }

        public int MaCt { get; set; }
        public int? Sttct { get; set; }
        public string MaChungTu { get; set; }
        public string MaKh { get; set; }
        public string LyDo { get; set; }
        public string SoBb { get; set; }
        public string SoHd { get; set; }
        public string UserNhap { get; set; }
        public string NhaMay { get; set; }
        public string GhiChu { get; set; }
        public DateTime? Ngay { get; set; }
        public int? SerialCttam { get; set; }
        public DateTime? NgayInsert { get; set; }

        public virtual KhachHang MaKhNavigation { get; set; }
        public virtual ICollection<KhoTpNk> KhoTpNk { get; set; }
    }
}