// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class KhoTpIntem
    {
        public int Serial { get; set; }
        public int ChungTu { get; set; }
        public string ArticleNumber { get; set; }
        public int SoLuong { get; set; }
        public DateTime Ngay { get; set; }
        public string Ponumber { get; set; }
        public string IdnumberParent { get; set; }
        public string UserNhap { get; set; }
        public int? CheckPrint { get; set; }
        public string Grouppallet { get; set; }
        public int? Sttpo { get; set; }
        public DateTime? NgayInsert { get; set; }
    }
}