// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class KhoTpNk
    {
        public int Serial { get; set; }
        public int? ChungTu { get; set; }
        public string MaSp { get; set; }
        public string ArticleNumber { get; set; }
        public string Idnumber { get; set; }
        public string SoHd { get; set; }
        public string Dvgc { get; set; }
        public string SoBb { get; set; }
        public double? Slnhap { get; set; }
        public double? SlthungNhap { get; set; }
        public double? Gia { get; set; }
        public string Dvt { get; set; }
        public DateTime? Ngay { get; set; }
        public string ViTri { get; set; }
        public string GroupPallet { get; set; }
        public string UserNhap { get; set; }
        public string Useredit { get; set; }
        public DateTime? NgayInsert { get; set; }
        public string GhiChu { get; set; }
        public string LyDo { get; set; }
        public string Kien { get; set; }
        public string NhaMay { get; set; }
        public double? CanNang { get; set; }
        public string DauTuan { get; set; }
        public string ArticleNumberId { get; set; }

        public virtual ArticleNumberProduct ArticleNumberNavigation { get; set; }
        public virtual KhoTpChungTu ChungTuNavigation { get; set; }
        public virtual SanPham MaSpNavigation { get; set; }
        public virtual KhoTpSoDo ViTriNavigation { get; set; }
    }
}