// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class KhoTpScanCt
    {
        public KhoTpScanCt()
        {
            KhoTpScanItem = new HashSet<KhoTpScanItem>();
        }

        public int Serial { get; set; }
        public string TenFile { get; set; }
        public string Cont { get; set; }
        public string Ponumber { get; set; }
        public string Seal { get; set; }
        public DateTime? Ngay { get; set; }
        public string UserNhap { get; set; }
        public DateTime? NgayInsert { get; set; }

        public virtual ICollection<KhoTpScanItem> KhoTpScanItem { get; set; }
    }
}