// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class KhoTpSoDo
    {
        public KhoTpSoDo()
        {
            KhoTpNk = new HashSet<KhoTpNk>();
            KhoTpViTri = new HashSet<KhoTpViTri>();
        }

        public string Hang { get; set; }
        public string ViTri { get; set; }
        public double? Cdai { get; set; }
        public double? Crong { get; set; }
        public double? Ccao { get; set; }
        public double? Kluong { get; set; }
        public string NhaMay { get; set; }
        public string Ke { get; set; }
        public string Day { get; set; }
        public string Pallet { get; set; }
        public string Tang { get; set; }

        public virtual ICollection<KhoTpNk> KhoTpNk { get; set; }
        public virtual ICollection<KhoTpViTri> KhoTpViTri { get; set; }
    }
}