// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class Kv4TonMb
    {
        public int Serial { get; set; }
        public string MaCt { get; set; }
        public double? Slnhap { get; set; }
        public double? Slxuat { get; set; }
        public string NhaMay { get; set; }
        public string LyDo { get; set; }
        public string ArticleNumber { get; set; }
        public string MaMau { get; set; }
        public DateTime? NgayInsert { get; set; }
        public string UserInsert { get; set; }
        public string TableName { get; set; }
        public int? SerialofTable { get; set; }
    }
}