// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class LichLamViec
    {
        public int Serial { get; set; }
        public DateTime? NgayBd { get; set; }
        public DateTime? NgayKt { get; set; }
        public string Email { get; set; }
        public string GhiChu { get; set; }
        public string UserInsert { get; set; }
        public int? HoanThanh { get; set; }
        public DateTime? NgayInsert { get; set; }
    }
}