// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class MaMau
    {
        public MaMau()
        {
            ArticleNumberProduct = new HashSet<ArticleNumberProduct>();
        }

        public int Serial { get; set; }
        public string MaMau1 { get; set; }
        public string TenMau { get; set; }
        public string Colorint { get; set; }
        public string Colorhex { get; set; }

        public virtual ICollection<ArticleNumberProduct> ArticleNumberProduct { get; set; }
    }
}