// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace APIServerNFC.Model
{
    public partial class NFCDBContext : DbContext
    {
        public NFCDBContext()
        {
        }

      

        public virtual DbSet<AndroidScanTempKtp> AndroidScanTempKtp { get; set; }
        public virtual DbSet<ArticleNumberProduct> ArticleNumberProduct { get; set; }
        public virtual DbSet<ArticleNumberProductGia> ArticleNumberProductGia { get; set; }
        public virtual DbSet<ChiTietKhuVuc> ChiTietKhuVuc { get; set; }
        public virtual DbSet<DataDropDownList> DataDropDownList { get; set; }
        public virtual DbSet<DeviceIdandroid> DeviceIdandroid { get; set; }
        public virtual DbSet<DonHangHoSoPo> DonHangHoSoPo { get; set; }
        public virtual DbSet<DonHangMua> DonHangMua { get; set; }
        public virtual DbSet<DonHangPiform> DonHangPiform { get; set; }
        public virtual DbSet<DonHangPisuaDoi> DonHangPisuaDoi { get; set; }
        public virtual DbSet<DonHangQckiem> DonHangQckiem { get; set; }
        public virtual DbSet<DonHangSoHd> DonHangSoHd { get; set; }
        public virtual DbSet<EmailList> EmailList { get; set; }
        public virtual DbSet<FileHoSo> FileHoSo { get; set; }
        public virtual DbSet<FileOfSoft> FileOfSoft { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<InvoiceHoSo> InvoiceHoSo { get; set; }
        public virtual DbSet<InvoiceItem> InvoiceItem { get; set; }
        public virtual DbSet<InvoiceItemOther> InvoiceItemOther { get; set; }
        public virtual DbSet<KeHoachJob> KeHoachJob { get; set; }
        public virtual DbSet<KeHoachNccchungTu> KeHoachNccchungTu { get; set; }
        public virtual DbSet<KeHoachNccitem> KeHoachNccitem { get; set; }
        public virtual DbSet<KeHoachNccitemSp> KeHoachNccitemSp { get; set; }
        public virtual DbSet<KeHoachXuatHang> KeHoachXuatHang { get; set; }
        public virtual DbSet<KeHoachXuatHangDel> KeHoachXuatHangDel { get; set; }
        public virtual DbSet<KhachHang> KhachHang { get; set; }
        public virtual DbSet<KhachHangShipto> KhachHangShipto { get; set; }
        public virtual DbSet<KhoChoRap> KhoChoRap { get; set; }
        public virtual DbSet<KhoChoSon> KhoChoSon { get; set; }
        public virtual DbSet<KhoTpChungTu> KhoTpChungTu { get; set; }
        public virtual DbSet<KhoTpChuyenPoLog> KhoTpChuyenPoLog { get; set; }
        public virtual DbSet<KhoTpHclyDo> KhoTpHclyDo { get; set; }
        public virtual DbSet<KhoTpInfoArt> KhoTpInfoArt { get; set; }
        public virtual DbSet<KhoTpIntem> KhoTpIntem { get; set; }
        public virtual DbSet<KhoTpNk> KhoTpNk { get; set; }
        public virtual DbSet<KhoTpNkDel> KhoTpNkDel { get; set; }
        public virtual DbSet<KhoTpNxnoiBo> KhoTpNxnoiBo { get; set; }
        public virtual DbSet<KhoTpScanCt> KhoTpScanCt { get; set; }
        public virtual DbSet<KhoTpScanItem> KhoTpScanItem { get; set; }
        public virtual DbSet<KhoTpSoDo> KhoTpSoDo { get; set; }
        public virtual DbSet<KhoTpTemPallet> KhoTpTemPallet { get; set; }
        public virtual DbSet<KhoTpViTri> KhoTpViTri { get; set; }
        public virtual DbSet<KhoTpXk> KhoTpXk { get; set; }
        public virtual DbSet<Kv4TonMb> Kv4TonMb { get; set; }
        public virtual DbSet<LichLamViec> LichLamViec { get; set; }
        public virtual DbSet<MaMau> MaMau { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCap { get; set; }
        public virtual DbSet<NhaCungCapFileHoSo> NhaCungCapFileHoSo { get; set; }
        public virtual DbSet<OsDonGia> OsDonGia { get; set; }
        public virtual DbSet<PhieuNhanDang> PhieuNhanDang { get; set; }
        public virtual DbSet<SanPham> SanPham { get; set; }
        public virtual DbSet<SanPhamChiTiet> SanPhamChiTiet { get; set; }
        public virtual DbSet<SanPhamPhanHe> SanPhamPhanHe { get; set; }
        public virtual DbSet<Testabc> Testabc { get; set; }
        public virtual DbSet<Users> Users { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<AndroidScanTempKtp>(entity =>
            {
                entity.HasKey(e => e.Serial);

                entity.ToTable("Android_ScanTempKTP");

                entity.Property(e => e.ArticleNumber).HasMaxLength(100);

                entity.Property(e => e.DauTuan).HasMaxLength(50);

                entity.Property(e => e.Idnumber)
                    .HasMaxLength(100)
                    .HasColumnName("IDNumber");

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.TenFile).HasMaxLength(100);

                entity.Property(e => e.UserInsert).HasMaxLength(100);
            });

            modelBuilder.Entity<ArticleNumberProduct>(entity =>
            {
                entity.HasKey(e => e.ArticleNumber);

                entity.Property(e => e.ArticleNumber).HasMaxLength(100);

                entity.Property(e => e.MaMau).HasMaxLength(100);

                entity.Property(e => e.MaSp)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("MaSP");

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Serial).ValueGeneratedOnAdd();

                entity.Property(e => e.Slpallet).HasColumnName("SLPallet");

                entity.Property(e => e.TypeOther)
                    .HasMaxLength(100)
                    .HasColumnName("Type_Other");

                entity.Property(e => e.UserInsert).HasMaxLength(100);

                entity.HasOne(d => d.MaMauNavigation)
                    .WithMany(p => p.ArticleNumberProduct)
                    .HasForeignKey(d => d.MaMau)
                    .HasConstraintName("FK_MaMau_Art");

                entity.HasOne(d => d.MaSpNavigation)
                    .WithMany(p => p.ArticleNumberProduct)
                    .HasForeignKey(d => d.MaSp)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ArticleNumberProduct_SanPham");
            });

            modelBuilder.Entity<ArticleNumberProductGia>(entity =>
            {
                entity.HasKey(e => e.Serial);

                entity.ToTable("ArticleNumberProduct_Gia");

                entity.Property(e => e.ArticleNumber).HasMaxLength(100);

                entity.Property(e => e.NgayBd)
                    .HasColumnType("date")
                    .HasColumnName("NgayBD");

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.NgayKt)
                    .HasColumnType("date")
                    .HasColumnName("NgayKT");

                entity.Property(e => e.UserInsert).HasMaxLength(100);
            });

            modelBuilder.Entity<ChiTietKhuVuc>(entity =>
            {
                entity.HasKey(e => e.Stt);

                entity.ToTable("ChiTiet_KhuVuc");

                entity.Property(e => e.Stt).HasColumnName("STT");

                entity.Property(e => e.ChonMot).HasMaxLength(100);

                entity.Property(e => e.KhuVuc)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.MaCt)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("MaCT");

                entity.Property(e => e.MaCtLink)
                    .HasMaxLength(100)
                    .HasColumnName("MaCT_link");

                entity.Property(e => e.MaSp)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("MaSP");

                entity.Property(e => e.SlctQuyDoi).HasColumnName("SLCT_QuyDoi");

                entity.Property(e => e.UserInsert).HasMaxLength(100);

                entity.HasOne(d => d.MaCtNavigation)
                    .WithMany(p => p.ChiTietKhuVuc)
                    .HasForeignKey(d => d.MaCt)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_SPCTKV");
            });

            modelBuilder.Entity<DataDropDownList>(entity =>
            {
                entity.HasKey(e => e.Serial);

                entity.Property(e => e.FullName).HasMaxLength(200);

                entity.Property(e => e.Name).HasMaxLength(100);

                entity.Property(e => e.TypeName).HasMaxLength(100);
            });

            modelBuilder.Entity<DeviceIdandroid>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("DeviceIDAndroid");

                entity.Property(e => e.DeviceId)
                    .HasMaxLength(1000)
                    .HasColumnName("DeviceID");

                entity.Property(e => e.DeviceName).HasMaxLength(1000);

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Serial).ValueGeneratedOnAdd();

                entity.Property(e => e.UserName).HasMaxLength(100);
            });

            modelBuilder.Entity<DonHangHoSoPo>(entity =>
            {
                entity.HasKey(e => e.Serial);

                entity.ToTable("DonHang_HoSoPO");

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.NhomHoSo).HasMaxLength(200);

                entity.Property(e => e.Ponumber)
                    .HasMaxLength(200)
                    .HasColumnName("PONumber");
            });

            modelBuilder.Entity<DonHangMua>(entity =>
            {
                entity.HasKey(e => e.Serial);

                entity.Property(e => e.ArticleNumber)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.GhiChu).HasMaxLength(200);

                entity.Property(e => e.MaHd)
                    .HasMaxLength(100)
                    .HasColumnName("MaHD");

                entity.Property(e => e.MaSp)
                    .HasMaxLength(100)
                    .HasColumnName("MaSP");

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.PhanLoai).HasMaxLength(100);

                entity.HasOne(d => d.ArticleNumberNavigation)
                    .WithMany(p => p.DonHangMua)
                    .HasForeignKey(d => d.ArticleNumber)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_DonHang_Article");
            });

            modelBuilder.Entity<DonHangPiform>(entity =>
            {
                entity.HasKey(e => e.Ponumber);

                entity.ToTable("DonHang_PIForm");

                entity.Property(e => e.Ponumber)
                    .HasMaxLength(100)
                    .HasColumnName("PONumber");

                entity.Property(e => e.DiaChi).HasMaxLength(500);

                entity.Property(e => e.DonHang).HasMaxLength(100);

                entity.Property(e => e.DraftPi)
                    .HasMaxLength(100)
                    .HasColumnName("DraftPI");

                entity.Property(e => e.Email)
                    .HasMaxLength(100)
                    .HasColumnName("EMail");

                entity.Property(e => e.Fax)
                    .HasMaxLength(50)
                    .HasColumnName("FAX");

                entity.Property(e => e.Forworder).HasMaxLength(200);

                entity.Property(e => e.GhiChu).HasMaxLength(100);

                entity.Property(e => e.HanThanhToan).HasMaxLength(100);

                entity.Property(e => e.KhoHang).HasMaxLength(100);

                entity.Property(e => e.LoaiCont).HasMaxLength(100);

                entity.Property(e => e.MaKh)
                    .HasMaxLength(100)
                    .HasColumnName("MaKH");

                entity.Property(e => e.MaNcc)
                    .HasMaxLength(100)
                    .HasColumnName("MaNCC");

                entity.Property(e => e.NgayDuKien).HasColumnType("date");

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.NgayKhyeuCau)
                    .HasColumnType("date")
                    .HasColumnName("NgayKHYeuCau");

                entity.Property(e => e.NgayNhanDonHang).HasColumnType("date");

                entity.Property(e => e.Serial).ValueGeneratedOnAdd();

                entity.Property(e => e.Tel)
                    .HasMaxLength(50)
                    .HasColumnName("TEL");

                entity.Property(e => e.ThoiGianGiao).HasMaxLength(100);

                entity.Property(e => e.UserInsert).HasMaxLength(100);

                entity.HasOne(d => d.MaNccNavigation)
                    .WithMany(p => p.DonHangPiform)
                    .HasForeignKey(d => d.MaNcc)
                    .HasConstraintName("FK_DonHang_PIForm_NhaCungCap");
            });

            modelBuilder.Entity<DonHangPisuaDoi>(entity =>
            {
                entity.HasKey(e => e.Serial);

                entity.ToTable("DonHang_PISuaDoi");

                entity.Property(e => e.LyDo).HasMaxLength(200);

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.NgayKhyeuCau)
                    .HasColumnType("date")
                    .HasColumnName("NgayKHYeuCau");

                entity.Property(e => e.NgayKhyeuCauOld)
                    .HasColumnType("date")
                    .HasColumnName("NgayKHYeuCauOld");

                entity.Property(e => e.Ponumber)
                    .HasMaxLength(100)
                    .HasColumnName("PONumber");

                entity.Property(e => e.UserNhap).HasMaxLength(100);
            });

            modelBuilder.Entity<DonHangQckiem>(entity =>
            {
                entity.HasKey(e => e.Serial);

                entity.ToTable("DonHang_QCKiem");

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.NgayKiem).HasColumnType("date");

                entity.Property(e => e.NguoiKiem).HasMaxLength(100);

                entity.Property(e => e.Ponumber)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("PONumber");

                entity.Property(e => e.UserInsert).HasMaxLength(100);
            });

            modelBuilder.Entity<DonHangSoHd>(entity =>
            {
                entity.HasKey(e => e.Serial);

                entity.ToTable("DonHang_SoHD");

                entity.Property(e => e.MaKh)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("MaKH");

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.SoHd)
                    .HasMaxLength(200)
                    .HasColumnName("SoHD");

                entity.Property(e => e.UserInsert).HasMaxLength(100);

                entity.HasOne(d => d.MaKhNavigation)
                    .WithMany(p => p.DonHangSoHd)
                    .HasForeignKey(d => d.MaKh)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("DF_DonHang_SoHD_KhachHang");
            });

            modelBuilder.Entity<EmailList>(entity =>
            {
                entity.HasNoKey();

                entity.Property(e => e.Email)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.FullName)
                    .IsRequired()
                    .HasMaxLength(150);

                entity.Property(e => e.Serial).ValueGeneratedOnAdd();
            });

            modelBuilder.Entity<FileHoSo>(entity =>
            {
                entity.HasKey(e => e.Serial);

                entity.Property(e => e.DienGiai).HasMaxLength(200);

                entity.Property(e => e.Dvt)
                    .HasMaxLength(100)
                    .HasColumnName("DVT");

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.TableName).HasMaxLength(200);

                entity.Property(e => e.TenFile).HasMaxLength(300);

                entity.Property(e => e.UserInsert).HasMaxLength(100);
            });

            modelBuilder.Entity<FileOfSoft>(entity =>
            {
                entity.HasKey(e => e.Serial);

                entity.ToTable("File_ofSoft");

                entity.Property(e => e.FileName).HasMaxLength(1000);

                entity.Property(e => e.FileSize).HasMaxLength(100);

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.UserInsert).HasMaxLength(100);
            });

            modelBuilder.Entity<Invoice>(entity =>
            {
                entity.HasKey(e => e.Serial);

                entity.Property(e => e.Cntr).HasMaxLength(1000);

                entity.Property(e => e.DiaChiDen).HasMaxLength(1000);

                entity.Property(e => e.GhiChu).HasMaxLength(1000);

                entity.Property(e => e.InvoiceNumber).HasMaxLength(100);

                entity.Property(e => e.MaKh)
                    .HasMaxLength(100)
                    .HasColumnName("MaKH");

                entity.Property(e => e.Mbl)
                    .HasMaxLength(1000)
                    .HasColumnName("MBL");

                entity.Property(e => e.NgayHenTra).HasColumnType("date");

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.NgayNhanHang).HasColumnType("date");

                entity.Property(e => e.NgayTauChay).HasColumnType("date");

                entity.Property(e => e.NgayTauDen).HasColumnType("date");

                entity.Property(e => e.NgayThanhToan).HasColumnType("date");

                entity.Property(e => e.NguoiLienHe).HasMaxLength(200);

                entity.Property(e => e.NoiDen).HasMaxLength(1000);

                entity.Property(e => e.Scaccode).HasMaxLength(1000);

                entity.Property(e => e.UserInsert).HasMaxLength(100);

                entity.Property(e => e.Vessel).HasMaxLength(1000);

                entity.HasOne(d => d.MaKhNavigation)
                    .WithMany(p => p.Invoice)
                    .HasForeignKey(d => d.MaKh)
                    .HasConstraintName("FK_Invoice_KhachHang");
            });

            modelBuilder.Entity<InvoiceHoSo>(entity =>
            {
                entity.HasKey(e => e.Serial);

                entity.ToTable("Invoice_HoSo");

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.NhomHoSo).HasMaxLength(200);

                entity.HasOne(d => d.SerialInvoiceNavigation)
                    .WithMany(p => p.InvoiceHoSo)
                    .HasForeignKey(d => d.SerialInvoice)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK_Invoice_HoSo_Invoice");
            });

            modelBuilder.Entity<InvoiceItem>(entity =>
            {
                entity.HasKey(e => e.Serial);

                entity.HasIndex(e => e.PonumberItem, "sqlUniquePONumberItem")
                    .IsUnique();

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.PonumberItem)
                    .HasMaxLength(100)
                    .HasColumnName("PONumberItem");

                entity.Property(e => e.UserInsert).HasMaxLength(100);

                entity.HasOne(d => d.SerialInvoiceNavigation)
                    .WithMany(p => p.InvoiceItem)
                    .HasForeignKey(d => d.SerialInvoice)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK_InvoiceItem_Invoice");
            });

            modelBuilder.Entity<InvoiceItemOther>(entity =>
            {
                entity.HasKey(e => e.Serial);

                entity.ToTable("Invoice_ItemOther");

                entity.Property(e => e.DienGiai).HasMaxLength(500);

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.UserInsert).HasMaxLength(100);

                entity.HasOne(d => d.SerialInvoiceNavigation)
                    .WithMany(p => p.InvoiceItemOther)
                    .HasForeignKey(d => d.SerialInvoice)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK_Invoice_ItemOther_Invoice");
            });

            modelBuilder.Entity<KeHoachJob>(entity =>
            {
                entity.HasKey(e => e.MaKeHoach);

                entity.ToTable("KeHoach_Job");

                entity.Property(e => e.MaKeHoach).HasMaxLength(100);

                entity.Property(e => e.ArticleNumber).HasMaxLength(100);

                entity.Property(e => e.ChuyenOs)
                    .HasMaxLength(100)
                    .HasColumnName("ChuyenOS");

                entity.Property(e => e.GhiChu).HasMaxLength(500);

                entity.Property(e => e.KhoChoRap).HasDefaultValueSql("((0))");

                entity.Property(e => e.KhoChoSon).HasDefaultValueSql("((0))");

                entity.Property(e => e.KhoTinhChe).HasDefaultValueSql("((0))");

                entity.Property(e => e.LoaiHang).HasMaxLength(100);

                entity.Property(e => e.MaNcc)
                    .HasMaxLength(100)
                    .HasColumnName("MaNCC");

                entity.Property(e => e.NgayBd)
                    .HasColumnType("date")
                    .HasColumnName("NgayBD");

                entity.Property(e => e.NgayBdgh)
                    .HasColumnType("date")
                    .HasColumnName("NgayBDGH");

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.NgayKt)
                    .HasColumnType("date")
                    .HasColumnName("NgayKT");

                entity.Property(e => e.NgayKtgh)
                    .HasColumnType("date")
                    .HasColumnName("NgayKTGH");

                entity.Property(e => e.OfnumberReport)
                    .HasMaxLength(100)
                    .HasColumnName("OFNumber_Report");

                entity.Property(e => e.Serial).ValueGeneratedOnAdd();

                entity.Property(e => e.Slkh).HasColumnName("SLKH");

                entity.Property(e => e.Sttkh).HasColumnName("STTKH");

                entity.Property(e => e.UserInsert).HasMaxLength(100);

                entity.HasOne(d => d.OfnumberReportNavigation)
                    .WithMany(p => p.KeHoachJob)
                    .HasForeignKey(d => d.OfnumberReport)
                    .HasConstraintName("FK_PONumberKH_PIForm");
            });

            modelBuilder.Entity<KeHoachNccchungTu>(entity =>
            {
                entity.HasKey(e => e.Serial)
                    .HasName("PK_KeHoach_ChungTuNCC");

                entity.ToTable("KeHoach_NCCChungTu");

                entity.Property(e => e.DienGiai).HasMaxLength(300);

                entity.Property(e => e.Duyet).HasMaxLength(100);

                entity.Property(e => e.LoaiHang).HasMaxLength(100);

                entity.Property(e => e.MaChungTu).HasMaxLength(50);

                entity.Property(e => e.MaNcc)
                    .HasMaxLength(100)
                    .HasColumnName("MaNCC");

                entity.Property(e => e.Ngay).HasColumnType("date");

                entity.Property(e => e.NgayBd)
                    .HasColumnType("date")
                    .HasColumnName("NgayBD");

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.NgayKt)
                    .HasColumnType("date")
                    .HasColumnName("NgayKT");

                entity.Property(e => e.Sttct).HasColumnName("STTCT");

                entity.Property(e => e.UserInsert).HasMaxLength(100);
            });

            modelBuilder.Entity<KeHoachNccitem>(entity =>
            {
                entity.HasKey(e => e.Serial);

                entity.ToTable("KeHoach_NCCItem");

                entity.Property(e => e.DienGiai).HasMaxLength(100);

                entity.Property(e => e.Dvt)
                    .HasMaxLength(50)
                    .HasColumnName("DVT");

                entity.Property(e => e.KhuVuc).HasMaxLength(100);

                entity.Property(e => e.MaChiTiet).HasMaxLength(100);

                entity.Property(e => e.MaKeHoach).HasMaxLength(100);

                entity.Property(e => e.MaSp)
                    .HasMaxLength(100)
                    .HasColumnName("MaSP");

                entity.Property(e => e.NgayBd)
                    .HasColumnType("date")
                    .HasColumnName("NgayBD");

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.NgayKt)
                    .HasColumnType("date")
                    .HasColumnName("NgayKT");

                entity.Property(e => e.SerialCt).HasColumnName("Serial_CT");

                entity.Property(e => e.SerialLinkItem).HasColumnName("Serial_LinkItem");

                entity.Property(e => e.Slnkcl).HasColumnName("SLNKCL");

                entity.Property(e => e.Slxkcl).HasColumnName("SLXKCL");

                entity.Property(e => e.UserInsert)
                    .HasMaxLength(100)
                    .HasDefaultValueSql("(getdate())");

                entity.HasOne(d => d.MaKeHoachNavigation)
                    .WithMany(p => p.KeHoachNccitem)
                    .HasForeignKey(d => d.MaKeHoach)
                    .HasConstraintName("FK_ItemCTJob");

                entity.HasOne(d => d.SerialCtNavigation)
                    .WithMany(p => p.KeHoachNccitem)
                    .HasForeignKey(d => d.SerialCt)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK_ItemCT");
            });

            modelBuilder.Entity<KeHoachNccitemSp>(entity =>
            {
                entity.HasKey(e => e.Serial);

                entity.ToTable("KeHoach_NCCItemSP");

                entity.Property(e => e.ArticleNumber).HasMaxLength(100);

                entity.Property(e => e.KhuVuc).HasMaxLength(100);

                entity.Property(e => e.MaKeHoach).HasMaxLength(100);

                entity.Property(e => e.MaSp)
                    .HasMaxLength(100)
                    .HasColumnName("MaSP");

                entity.Property(e => e.SerialCt).HasColumnName("Serial_CT");

                entity.Property(e => e.SerialLinkItem).HasColumnName("Serial_LinkItem");

                entity.Property(e => e.Slkh).HasColumnName("SLKH");

                entity.HasOne(d => d.MaKeHoachNavigation)
                    .WithMany(p => p.KeHoachNccitemSp)
                    .HasForeignKey(d => d.MaKeHoach)
                    .HasConstraintName("FK_ItemCTJobSP");

                entity.HasOne(d => d.SerialCtNavigation)
                    .WithMany(p => p.KeHoachNccitemSp)
                    .HasForeignKey(d => d.SerialCt)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK_ItemCTSP");
            });

            modelBuilder.Entity<KeHoachXuatHang>(entity =>
            {
                entity.HasKey(e => e.Serial);

                entity.Property(e => e.ArticleNumber)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.Booking).HasColumnType("date");

                entity.Property(e => e.Cont)
                    .HasMaxLength(100)
                    .HasDefaultValueSql("('')");

                entity.Property(e => e.Conumber)
                    .HasMaxLength(300)
                    .HasColumnName("CONumber")
                    .HasDefaultValueSql("('')");

                entity.Property(e => e.CuaHangDen)
                    .HasMaxLength(1000)
                    .HasDefaultValueSql("('')");

                entity.Property(e => e.DaKiem)
                    .HasMaxLength(100)
                    .HasDefaultValueSql("('')");

                entity.Property(e => e.DaXuat).HasDefaultValueSql("((0))");

                entity.Property(e => e.DienGiai).HasDefaultValueSql("('')");

                entity.Property(e => e.DonHang)
                    .HasMaxLength(200)
                    .HasDefaultValueSql("('')");

                entity.Property(e => e.Draft).HasMaxLength(100);

                entity.Property(e => e.Eta)
                    .HasColumnType("date")
                    .HasColumnName("ETA");

                entity.Property(e => e.Etd)
                    .HasColumnType("date")
                    .HasColumnName("ETD");

                entity.Property(e => e.GhiChu).HasDefaultValueSql("('')");

                entity.Property(e => e.InvoiceNumber)
                    .HasMaxLength(100)
                    .HasDefaultValueSql("('')");

                entity.Property(e => e.KhachHang).HasMaxLength(100);

                entity.Property(e => e.KhoDen)
                    .HasMaxLength(1000)
                    .HasDefaultValueSql("('')");

                entity.Property(e => e.KhoDuKien)
                    .HasMaxLength(1000)
                    .HasDefaultValueSql("('')");

                entity.Property(e => e.LenCont)
                    .HasMaxLength(50)
                    .HasDefaultValueSql("('')");

                entity.Property(e => e.LoaiCont)
                    .HasMaxLength(100)
                    .HasDefaultValueSql("('')");

                entity.Property(e => e.LoaiGo)
                    .HasMaxLength(100)
                    .HasDefaultValueSql("('')");

                entity.Property(e => e.LoaiKhoDen).HasMaxLength(1000);

                entity.Property(e => e.LoaiKhoDuKien)
                    .HasMaxLength(1000)
                    .HasDefaultValueSql("('')");

                entity.Property(e => e.MucDo).HasDefaultValueSql("((0))");

                entity.Property(e => e.NgayDuKien).HasColumnType("date");

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.NgayKhyeuCau)
                    .HasColumnType("date")
                    .HasColumnName("NgayKHYeuCau");

                entity.Property(e => e.NgayNhanDonHang).HasColumnType("date");

                entity.Property(e => e.NgayXuat).HasColumnType("date");

                entity.Property(e => e.NhaMay)
                    .HasMaxLength(100)
                    .HasDefaultValueSql("('')");

                entity.Property(e => e.Ofnumber)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("OFNumber")
                    .HasDefaultValueSql("('')");

                entity.Property(e => e.OfnumberReport)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("OFNumber_Report")
                    .HasDefaultValueSql("('')");

                entity.Property(e => e.QuocGia).HasMaxLength(100);

                entity.Property(e => e.Rmcode)
                    .HasMaxLength(200)
                    .HasColumnName("RMCode")
                    .HasDefaultValueSql("('')");

                entity.Property(e => e.SldaXuat).HasColumnName("SLDaXuat");

                entity.Property(e => e.SldatHang).HasColumnName("SLDatHang");

                entity.Property(e => e.SldonHang).HasColumnName("SLDonHang");

                entity.Property(e => e.Slhuy).HasColumnName("SLHuy");

                entity.Property(e => e.SoHd)
                    .HasMaxLength(100)
                    .HasColumnName("SoHD")
                    .HasDefaultValueSql("('')");

                entity.Property(e => e.TenSp)
                    .HasColumnName("TenSP")
                    .HasDefaultValueSql("('')");

                entity.Property(e => e.Transit)
                    .HasMaxLength(100)
                    .HasDefaultValueSql("('')");

                entity.Property(e => e.Type)
                    .HasMaxLength(100)
                    .HasDefaultValueSql("('')");

                entity.Property(e => e.UserInsert).HasMaxLength(100);

                entity.HasOne(d => d.ArticleNumberNavigation)
                    .WithMany(p => p.KeHoachXuatHang)
                    .HasForeignKey(d => d.ArticleNumber)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_KeHoachXuatHang_ArticleNumberProduct");

                entity.HasOne(d => d.OfnumberReportNavigation)
                    .WithMany(p => p.KeHoachXuatHang)
                    .HasForeignKey(d => d.OfnumberReport)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_PONumber_PIForm");
            });

            modelBuilder.Entity<KeHoachXuatHangDel>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("KeHoachXuatHang_del");

                entity.Property(e => e.ArticleNumber).HasMaxLength(100);

                entity.Property(e => e.Booking).HasColumnType("date");

                entity.Property(e => e.Conumber)
                    .HasMaxLength(100)
                    .HasColumnName("CONumber");

                entity.Property(e => e.CuaHangDen).HasMaxLength(1000);

                entity.Property(e => e.DaKiem).HasMaxLength(100);

                entity.Property(e => e.DonHang).HasMaxLength(100);

                entity.Property(e => e.Eta)
                    .HasColumnType("date")
                    .HasColumnName("ETA");

                entity.Property(e => e.Etd)
                    .HasColumnType("date")
                    .HasColumnName("ETD");

                entity.Property(e => e.KhachHang).HasMaxLength(100);

                entity.Property(e => e.KhoDen).HasMaxLength(1000);

                entity.Property(e => e.KhoDuKien).HasMaxLength(1000);

                entity.Property(e => e.LenCont).HasMaxLength(50);

                entity.Property(e => e.LoaiCont).HasMaxLength(100);

                entity.Property(e => e.LoaiGo).HasMaxLength(100);

                entity.Property(e => e.LoaiKhoDen).HasMaxLength(1000);

                entity.Property(e => e.LoaiKhoDuKien).HasMaxLength(1000);

                entity.Property(e => e.NgayDuKien).HasColumnType("date");

                entity.Property(e => e.NgayInsert).HasColumnType("datetime");

                entity.Property(e => e.NgayInsertDel)
                    .HasColumnType("datetime")
                    .HasColumnName("NgayInsert_del")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.NgayKhyeuCau)
                    .HasColumnType("date")
                    .HasColumnName("NgayKHYeuCau");

                entity.Property(e => e.NgayNhanDonHang).HasColumnType("date");

                entity.Property(e => e.NgayXuat).HasColumnType("date");

                entity.Property(e => e.NhaMay).HasMaxLength(100);

                entity.Property(e => e.Ofnumber)
                    .HasMaxLength(100)
                    .HasColumnName("OFNumber");

                entity.Property(e => e.OfnumberReport)
                    .HasMaxLength(100)
                    .HasColumnName("OFNumber_Report");

                entity.Property(e => e.QuocGia).HasMaxLength(100);

                entity.Property(e => e.SldaXuat).HasColumnName("SLDaXuat");

                entity.Property(e => e.SldatHang).HasColumnName("SLDatHang");

                entity.Property(e => e.SldonHang).HasColumnName("SLDonHang");

                entity.Property(e => e.Slhuy).HasColumnName("SLHuy");

                entity.Property(e => e.SoHd)
                    .HasMaxLength(100)
                    .HasColumnName("SoHD");

                entity.Property(e => e.TenSp).HasColumnName("TenSP");

                entity.Property(e => e.Transit).HasMaxLength(100);

                entity.Property(e => e.Type).HasMaxLength(100);
            });

            modelBuilder.Entity<KhachHang>(entity =>
            {
                entity.HasKey(e => e.MaKh);

                entity.Property(e => e.MaKh)
                    .HasMaxLength(100)
                    .HasColumnName("MaKH");

                entity.Property(e => e.DaiDienPl)
                    .HasMaxLength(1000)
                    .HasColumnName("DaiDienPL");

                entity.Property(e => e.DiDong).HasMaxLength(15);

                entity.Property(e => e.DiaChi).HasMaxLength(1000);

                entity.Property(e => e.DienThoaiBan).HasMaxLength(20);

                entity.Property(e => e.Email).HasMaxLength(100);

                entity.Property(e => e.LoaiHinhKinhDoanh).HasMaxLength(1000);

                entity.Property(e => e.MaSoThue).HasMaxLength(15);

                entity.Property(e => e.NguoiLh)
                    .HasMaxLength(100)
                    .HasColumnName("NguoiLH");

                entity.Property(e => e.QuocGia).HasMaxLength(200);

                entity.Property(e => e.Serial).ValueGeneratedOnAdd();

                entity.Property(e => e.SoFax).HasMaxLength(20);

                entity.Property(e => e.SoTk)
                    .HasMaxLength(100)
                    .HasColumnName("SoTK");

                entity.Property(e => e.TenKh)
                    .IsRequired()
                    .HasMaxLength(300)
                    .HasColumnName("TenKH");

                entity.Property(e => e.TenNh)
                    .HasMaxLength(100)
                    .HasColumnName("TenNH");

                entity.Property(e => e.TinhThanh).HasMaxLength(1000);

                entity.Property(e => e.UserInsert).HasMaxLength(100);

                entity.Property(e => e.Website).HasMaxLength(1000);
            });

            modelBuilder.Entity<KhachHangShipto>(entity =>
            {
                entity.HasKey(e => e.Stt);

                entity.ToTable("KhachHang_Shipto");

                entity.Property(e => e.Stt).HasColumnName("STT");

                entity.Property(e => e.Address1).HasMaxLength(500);

                entity.Property(e => e.Address2).HasMaxLength(1000);

                entity.Property(e => e.MaKh)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("MaKH");

                entity.Property(e => e.TenKh)
                    .HasMaxLength(300)
                    .HasColumnName("TenKH");
            });

            modelBuilder.Entity<KhoChoRap>(entity =>
            {
                entity.HasKey(e => e.Serial);

                entity.Property(e => e.ArticleNumber).HasMaxLength(100);

                entity.Property(e => e.ChatLuong).HasMaxLength(100);

                entity.Property(e => e.GhiChu).HasMaxLength(200);

                entity.Property(e => e.LoaiHang).HasMaxLength(100);

                entity.Property(e => e.LyDo).HasMaxLength(100);

                entity.Property(e => e.MaCt)
                    .HasMaxLength(100)
                    .HasColumnName("MaCT");

                entity.Property(e => e.MaKehoach).HasMaxLength(100);

                entity.Property(e => e.MauSp)
                    .HasMaxLength(100)
                    .HasColumnName("MauSP");

                entity.Property(e => e.Ngay).HasColumnType("date");

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.NhaMay).HasMaxLength(100);

                entity.Property(e => e.NoiGiao).HasMaxLength(100);

                entity.Property(e => e.NoiNhan).HasMaxLength(100);

                entity.Property(e => e.SerialKeHoach).HasColumnName("Serial_KeHoach");

                entity.Property(e => e.Slnhap).HasColumnName("SLNhap");

                entity.Property(e => e.Slxuat).HasColumnName("SLXuat");

                entity.Property(e => e.UserNhap).HasMaxLength(100);

                entity.HasOne(d => d.SerialKeHoachNavigation)
                    .WithMany(p => p.KhoChoRap)
                    .HasForeignKey(d => d.SerialKeHoach)
                    .HasConstraintName("FK_KhoChoRap_KeHoach");
            });

            modelBuilder.Entity<KhoChoSon>(entity =>
            {
                entity.HasNoKey();

                entity.Property(e => e.ArticleNumber).HasMaxLength(100);

                entity.Property(e => e.ChatLuong).HasMaxLength(100);

                entity.Property(e => e.GhiChu).HasMaxLength(200);

                entity.Property(e => e.LoaiHang).HasMaxLength(100);

                entity.Property(e => e.LyDo).HasMaxLength(100);

                entity.Property(e => e.MaCt)
                    .HasMaxLength(100)
                    .HasColumnName("MaCT");

                entity.Property(e => e.MaKehoach).HasMaxLength(100);

                entity.Property(e => e.MauSp)
                    .HasMaxLength(100)
                    .HasColumnName("MauSP");

                entity.Property(e => e.Ngay).HasColumnType("date");

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.NhaMay).HasMaxLength(100);

                entity.Property(e => e.NoiGiao).HasMaxLength(100);

                entity.Property(e => e.NoiNhan).HasMaxLength(100);

                entity.Property(e => e.Serial).ValueGeneratedOnAdd();

                entity.Property(e => e.SerialKeHoach).HasColumnName("Serial_KeHoach");

                entity.Property(e => e.Slnhap).HasColumnName("SLNhap");

                entity.Property(e => e.Slxuat).HasColumnName("SLXuat");

                entity.Property(e => e.UserNhap).HasMaxLength(100);

                entity.HasOne(d => d.SerialKeHoachNavigation)
                    .WithMany()
                    .HasForeignKey(d => d.SerialKeHoach)
                    .HasConstraintName("FK_KhoChoSon_KeHoach");
            });

            modelBuilder.Entity<KhoTpChungTu>(entity =>
            {
                entity.HasKey(e => e.MaCt);

                entity.ToTable("KhoTP_ChungTu");

                entity.Property(e => e.MaCt).HasColumnName("MaCT");

                entity.Property(e => e.GhiChu).HasMaxLength(200);

                entity.Property(e => e.LyDo).HasMaxLength(100);

                entity.Property(e => e.MaChungTu).HasMaxLength(100);

                entity.Property(e => e.MaKh)
                    .HasMaxLength(100)
                    .HasColumnName("MaKH");

                entity.Property(e => e.Ngay)
                    .HasColumnType("date")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.NhaMay).HasMaxLength(100);

                entity.Property(e => e.SerialCttam).HasColumnName("Serial_CTTam");

                entity.Property(e => e.SoBb).HasColumnName("SoBB");

                entity.Property(e => e.SoHd)
                    .HasMaxLength(50)
                    .HasColumnName("SoHD");

                entity.Property(e => e.Sttct).HasColumnName("STTCT");

                entity.Property(e => e.UserNhap).HasMaxLength(100);

                entity.HasOne(d => d.MaKhNavigation)
                    .WithMany(p => p.KhoTpChungTu)
                    .HasForeignKey(d => d.MaKh)
                    .HasConstraintName("FK_KhachHang_CTXK");
            });

            modelBuilder.Entity<KhoTpChuyenPoLog>(entity =>
            {
                entity.HasKey(e => e.Serial);

                entity.ToTable("KhoTP_ChuyenPO_Log");

                entity.Property(e => e.GhiChu).HasMaxLength(1000);

                entity.Property(e => e.Idnumber)
                    .HasMaxLength(100)
                    .HasColumnName("IDNumber");

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.PoNew)
                    .HasMaxLength(100)
                    .HasColumnName("PO_new");

                entity.Property(e => e.PoOld)
                    .HasMaxLength(100)
                    .HasColumnName("PO_old");

                entity.Property(e => e.UserInsert).HasMaxLength(100);
            });

            modelBuilder.Entity<KhoTpHclyDo>(entity =>
            {
                entity.HasKey(e => e.Serial);

                entity.ToTable("KhoTP_HCLyDo");

                entity.Property(e => e.ArticleNumber).HasMaxLength(100);

                entity.Property(e => e.LyDo).HasMaxLength(100);

                entity.Property(e => e.MaSp)
                    .HasMaxLength(100)
                    .HasColumnName("MaSP");

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Slhc).HasColumnName("SLHC");

                entity.Property(e => e.SoBb)
                    .HasMaxLength(500)
                    .HasColumnName("SoBB");
            });

            modelBuilder.Entity<KhoTpInfoArt>(entity =>
            {
                entity.HasKey(e => e.Serial);

                entity.ToTable("KhoTP_InfoArt");

                entity.Property(e => e.ArticleNumber).HasMaxLength(100);

                entity.Property(e => e.Cbm).HasColumnName("CBM");

                entity.Property(e => e.DateBegin).HasColumnType("date");

                entity.Property(e => e.DateEnd).HasColumnType("date");

                entity.Property(e => e.Hscode)
                    .HasMaxLength(50)
                    .HasColumnName("HSCode");

                entity.Property(e => e.ItemNo).HasMaxLength(100);

                entity.HasOne(d => d.ArticleNumberNavigation)
                    .WithMany(p => p.KhoTpInfoArt)
                    .HasForeignKey(d => d.ArticleNumber)
                    .HasConstraintName("FK_Art_Artproduct");
            });

            modelBuilder.Entity<KhoTpIntem>(entity =>
            {
                entity.HasKey(e => e.Serial)
                    .HasName("PK_InTem_KTP");

                entity.ToTable("KhoTP_Intem");

                entity.Property(e => e.ArticleNumber)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.Grouppallet).HasMaxLength(100);

                entity.Property(e => e.IdnumberParent)
                    .HasMaxLength(100)
                    .HasColumnName("IDNumberParent");

                entity.Property(e => e.Ngay).HasColumnType("date");

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Ponumber)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("PONumber");

                entity.Property(e => e.Sttpo).HasColumnName("STTPO");

                entity.Property(e => e.UserNhap).HasMaxLength(100);
            });

            modelBuilder.Entity<KhoTpNk>(entity =>
            {
                entity.HasKey(e => e.Idnumber)
                    .HasName("PK_KhoTP");

                entity.ToTable("KhoTP_NK");

                entity.Property(e => e.Idnumber)
                    .HasMaxLength(50)
                    .HasColumnName("IDNumber");

                entity.Property(e => e.ArticleNumber).HasMaxLength(50);

                entity.Property(e => e.ArticleNumberId)
                    .HasMaxLength(100)
                    .HasColumnName("ArticleNumberID");

                entity.Property(e => e.DauTuan).HasMaxLength(8);

                entity.Property(e => e.Dvgc)
                    .HasMaxLength(100)
                    .HasColumnName("DVGC");

                entity.Property(e => e.Dvt)
                    .HasMaxLength(50)
                    .HasColumnName("DVT");

                entity.Property(e => e.GhiChu).HasMaxLength(150);

                entity.Property(e => e.GroupPallet).HasMaxLength(20);

                entity.Property(e => e.Kien).HasMaxLength(30);

                entity.Property(e => e.LyDo).HasMaxLength(100);

                entity.Property(e => e.MaSp)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("MaSP");

                entity.Property(e => e.Ngay).HasColumnType("date");

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.NhaMay).HasMaxLength(100);

                entity.Property(e => e.Serial).ValueGeneratedOnAdd();

                entity.Property(e => e.Slnhap).HasColumnName("SLNhap");

                entity.Property(e => e.SlthungNhap).HasColumnName("SLThungNhap");

                entity.Property(e => e.SoBb)
                    .HasMaxLength(100)
                    .HasColumnName("SoBB");

                entity.Property(e => e.SoHd)
                    .HasMaxLength(100)
                    .HasColumnName("SoHD");

                entity.Property(e => e.UserNhap).HasMaxLength(100);

                entity.Property(e => e.Useredit).HasMaxLength(100);

                entity.Property(e => e.ViTri).HasMaxLength(20);

                entity.HasOne(d => d.ArticleNumberNavigation)
                    .WithMany(p => p.KhoTpNk)
                    .HasForeignKey(d => d.ArticleNumberId)
                    .HasConstraintName("FK_KTP_Article");

                entity.HasOne(d => d.ChungTuNavigation)
                    .WithMany(p => p.KhoTpNk)
                    .HasForeignKey(d => d.ChungTu)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK_ChungTu_NKTP");

                entity.HasOne(d => d.MaSpNavigation)
                    .WithMany(p => p.KhoTpNk)
                    .HasForeignKey(d => d.MaSp)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_KTP_SP");

                entity.HasOne(d => d.ViTriNavigation)
                    .WithMany(p => p.KhoTpNk)
                    .HasForeignKey(d => d.ViTri)
                    .HasConstraintName("FK_KTP_ViTri");
            });

            modelBuilder.Entity<KhoTpNkDel>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("KhoTP_NK_del");

                entity.Property(e => e.ArticleNumber).HasMaxLength(50);

                entity.Property(e => e.Dvgc)
                    .HasMaxLength(100)
                    .HasColumnName("DVGC");

                entity.Property(e => e.Dvt)
                    .HasMaxLength(50)
                    .HasColumnName("DVT");

                entity.Property(e => e.GhiChu).HasMaxLength(150);

                entity.Property(e => e.Idnumber)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("IDNumber");

                entity.Property(e => e.Kien).HasMaxLength(30);

                entity.Property(e => e.LyDo).HasMaxLength(100);

                entity.Property(e => e.MaSp)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("MaSP");

                entity.Property(e => e.Ngay).HasColumnType("datetime");

                entity.Property(e => e.NgayInsert).HasColumnType("datetime");

                entity.Property(e => e.NgayInsertDel)
                    .HasColumnType("datetime")
                    .HasColumnName("NgayInsert_Del")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.NhaMay).HasMaxLength(100);

                entity.Property(e => e.Slnhap).HasColumnName("SLNhap");

                entity.Property(e => e.SlthungNhap).HasColumnName("SLThungNhap");

                entity.Property(e => e.SoBb)
                    .HasMaxLength(100)
                    .HasColumnName("SoBB");

                entity.Property(e => e.SoHd)
                    .HasMaxLength(100)
                    .HasColumnName("SoHD");

                entity.Property(e => e.UserNhap).HasMaxLength(100);

                entity.Property(e => e.Useredit).HasMaxLength(100);

                entity.Property(e => e.ViTri).HasMaxLength(20);
            });

            modelBuilder.Entity<KhoTpNxnoiBo>(entity =>
            {
                entity.HasKey(e => e.Serial);

                entity.ToTable("KhoTP_NXNoiBo");

                entity.Property(e => e.GhiChu).HasMaxLength(150);

                entity.Property(e => e.Idnumber)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("IDNumber");

                entity.Property(e => e.KhachHang).HasMaxLength(100);

                entity.Property(e => e.Ngay).HasColumnType("date");

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.NoiNhan).HasMaxLength(100);

                entity.Property(e => e.Slnhap).HasColumnName("SLNhap");

                entity.Property(e => e.Slxuat).HasColumnName("SLXuat");

                entity.Property(e => e.UserNhap).HasMaxLength(100);
            });

            modelBuilder.Entity<KhoTpScanCt>(entity =>
            {
                entity.HasKey(e => e.Serial)
                    .HasName("PK_KhoTP_XuatLenCont");

                entity.ToTable("KhoTP_ScanCT");

                entity.Property(e => e.Cont).HasMaxLength(100);

                entity.Property(e => e.Ngay).HasColumnType("date");

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Ponumber).HasColumnName("PONumber");

                entity.Property(e => e.Seal).HasMaxLength(100);

                entity.Property(e => e.TenFile).HasMaxLength(200);

                entity.Property(e => e.UserNhap).HasMaxLength(100);
            });

            modelBuilder.Entity<KhoTpScanItem>(entity =>
            {
                entity.HasKey(e => e.Serial);

                entity.ToTable("KhoTP_ScanItem");

                entity.Property(e => e.Idnumber)
                    .HasMaxLength(100)
                    .HasColumnName("IDNumber");

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.SerialCt).HasColumnName("Serial_CT");

                entity.HasOne(d => d.SerialCtNavigation)
                    .WithMany(p => p.KhoTpScanItem)
                    .HasForeignKey(d => d.SerialCt)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ItemScan");
            });

            modelBuilder.Entity<KhoTpSoDo>(entity =>
            {
                entity.HasKey(e => e.ViTri);

                entity.ToTable("KhoTP_SoDo");

                entity.Property(e => e.ViTri).HasMaxLength(20);

                entity.Property(e => e.Ccao).HasColumnName("CCao");

                entity.Property(e => e.Cdai).HasColumnName("CDai");

                entity.Property(e => e.Crong).HasColumnName("CRong");

                entity.Property(e => e.Day).HasMaxLength(10);

                entity.Property(e => e.Hang).HasMaxLength(20);

                entity.Property(e => e.Ke).HasMaxLength(10);

                entity.Property(e => e.Kluong).HasColumnName("KLuong");

                entity.Property(e => e.NhaMay).HasMaxLength(50);

                entity.Property(e => e.Pallet).HasMaxLength(10);

                entity.Property(e => e.Tang).HasMaxLength(10);
            });

            modelBuilder.Entity<KhoTpTemPallet>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("KhoTP_TemPallet");

                entity.Property(e => e.GhiChu).HasMaxLength(100);

                entity.Property(e => e.Serial).ValueGeneratedOnAdd();
            });

            modelBuilder.Entity<KhoTpViTri>(entity =>
            {
                entity.HasKey(e => e.Serial);

                entity.ToTable("KhoTP_ViTri");

                entity.Property(e => e.GroupPallet).HasMaxLength(100);

                entity.Property(e => e.Idnumber)
                    .HasMaxLength(100)
                    .HasColumnName("IDNumber");

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.UserNhap).HasMaxLength(100);

                entity.Property(e => e.ViTri).HasMaxLength(20);

                entity.HasOne(d => d.ViTriNavigation)
                    .WithMany(p => p.KhoTpViTri)
                    .HasForeignKey(d => d.ViTri)
                    .HasConstraintName("FK_KTP_SoDo");
            });

            modelBuilder.Entity<KhoTpXk>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("KhoTP_XK");

                entity.HasIndex(e => e.Idnumber, "UQ__KhoTP_XK__564DB08AB3277779")
                    .IsUnique();

                entity.Property(e => e.GhiChu).HasMaxLength(150);

                entity.Property(e => e.Idnumber)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("IDNumber");

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Serial).ValueGeneratedOnAdd();

                entity.HasOne(d => d.ChungTuNavigation)
                    .WithMany()
                    .HasForeignKey(d => d.ChungTu)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK_ChungTu");

                entity.HasOne(d => d.IdnumberNavigation)
                    .WithOne()
                    .HasForeignKey<KhoTpXk>(d => d.Idnumber)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_IDNumber");
            });

            modelBuilder.Entity<Kv4TonMb>(entity =>
            {
                entity.HasKey(e => e.Serial);

                entity.ToTable("KV4_TonMB");

                entity.Property(e => e.ArticleNumber).HasMaxLength(100);

                entity.Property(e => e.LyDo).HasMaxLength(100);

                entity.Property(e => e.MaCt)
                    .HasMaxLength(100)
                    .HasColumnName("MaCT");

                entity.Property(e => e.MaMau).HasMaxLength(100);

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.NhaMay).HasMaxLength(100);

                entity.Property(e => e.Slnhap)
                    .HasColumnName("SLNhap")
                    .HasDefaultValueSql("((0))");

                entity.Property(e => e.Slxuat)
                    .HasColumnName("SLXuat")
                    .HasDefaultValueSql("((0))");

                entity.Property(e => e.TableName).HasMaxLength(100);

                entity.Property(e => e.UserInsert).HasMaxLength(100);
            });

            modelBuilder.Entity<LichLamViec>(entity =>
            {
                entity.HasKey(e => e.Serial);

                entity.Property(e => e.NgayBd)
                    .HasColumnType("date")
                    .HasColumnName("NgayBD");

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.NgayKt)
                    .HasColumnType("date")
                    .HasColumnName("NgayKT");

                entity.Property(e => e.UserInsert).HasMaxLength(100);
            });

            modelBuilder.Entity<MaMau>(entity =>
            {
                entity.HasKey(e => e.MaMau1);

                entity.Property(e => e.MaMau1)
                    .HasMaxLength(100)
                    .HasColumnName("MaMau");

                entity.Property(e => e.Colorhex).HasMaxLength(50);

                entity.Property(e => e.Colorint).HasMaxLength(50);

                entity.Property(e => e.Serial).ValueGeneratedOnAdd();

                entity.Property(e => e.TenMau).HasMaxLength(100);
            });

            modelBuilder.Entity<NhaCungCap>(entity =>
            {
                entity.HasKey(e => e.MaNcc);

                entity.Property(e => e.MaNcc)
                    .HasMaxLength(100)
                    .HasColumnName("MaNCC");

                entity.Property(e => e.ChungChiCoC).HasMaxLength(1000);

                entity.Property(e => e.DaiDienPl)
                    .HasMaxLength(200)
                    .HasColumnName("DaiDienPL");

                entity.Property(e => e.DiDong).HasMaxLength(20);

                entity.Property(e => e.DiaChi).HasMaxLength(300);

                entity.Property(e => e.DienThoaiBan).HasMaxLength(20);

                entity.Property(e => e.Email).HasMaxLength(1000);

                entity.Property(e => e.LoaiHinhKinhDoanh).HasMaxLength(200);

                entity.Property(e => e.MaSoThue).HasMaxLength(100);

                entity.Property(e => e.NguoiLh)
                    .HasMaxLength(1000)
                    .HasColumnName("NguoiLH");

                entity.Property(e => e.QuocGia).HasMaxLength(200);

                entity.Property(e => e.Serial).ValueGeneratedOnAdd();

                entity.Property(e => e.SoFax).HasMaxLength(20);

                entity.Property(e => e.SoTk)
                    .HasMaxLength(20)
                    .HasColumnName("SoTK");

                entity.Property(e => e.TenNcc)
                    .HasMaxLength(200)
                    .HasColumnName("TenNCC");

                entity.Property(e => e.TenNh)
                    .HasMaxLength(100)
                    .HasColumnName("TenNH");

                entity.Property(e => e.TenVietTat).HasMaxLength(500);

                entity.Property(e => e.TinhThanh).HasMaxLength(1000);

                entity.Property(e => e.UserInsert).HasMaxLength(100);

                entity.Property(e => e.Website).HasMaxLength(1000);
            });

            modelBuilder.Entity<NhaCungCapFileHoSo>(entity =>
            {
                entity.HasKey(e => e.Serial);

                entity.ToTable("NhaCungCap_FileHoSo");

                entity.Property(e => e.DungLuong).HasMaxLength(20);

                entity.Property(e => e.MaNcc)
                    .HasMaxLength(100)
                    .HasColumnName("MaNCC");

                entity.Property(e => e.NgayHetHan).HasColumnType("date");

                entity.Property(e => e.NgayHieuLuc).HasColumnType("date");

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.NguoiDuyet).HasMaxLength(100);

                entity.Property(e => e.TenHoSo).HasMaxLength(200);

                entity.Property(e => e.UserInsert).HasMaxLength(100);
            });

            modelBuilder.Entity<OsDonGia>(entity =>
            {
                entity.HasKey(e => e.Serial);

                entity.ToTable("OS_DonGia");

                entity.Property(e => e.KhuVuc).HasMaxLength(100);

                entity.Property(e => e.MaChiTiet).HasMaxLength(100);

                entity.Property(e => e.NgayHieuLuc).HasColumnType("date");

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.UserInsert).HasMaxLength(100);
            });

            modelBuilder.Entity<PhieuNhanDang>(entity =>
            {
                entity.HasKey(e => e.Serial);

                entity.Property(e => e.LoaiHang).HasMaxLength(100);

                entity.Property(e => e.MaCt)
                    .HasMaxLength(100)
                    .HasColumnName("MaCT");

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Ponumber)
                    .HasMaxLength(100)
                    .HasColumnName("PONumber");

                entity.Property(e => e.UserInsert).HasMaxLength(100);
            });

            modelBuilder.Entity<SanPham>(entity =>
            {
                entity.HasKey(e => e.MaSp);

                entity.Property(e => e.MaSp)
                    .HasMaxLength(100)
                    .HasColumnName("MaSP");

                entity.Property(e => e.Ccao).HasColumnName("CCao");

                entity.Property(e => e.Cdai).HasColumnName("CDai");

                entity.Property(e => e.Crong).HasColumnName("CRong");

                entity.Property(e => e.DienGiai).HasMaxLength(200);

                entity.Property(e => e.Equ)
                    .HasColumnName("EQU")
                    .HasDefaultValueSql("((0))");

                entity.Property(e => e.He).HasMaxLength(100);

                entity.Property(e => e.KhachHang).HasMaxLength(100);

                entity.Property(e => e.LoaiGo).HasMaxLength(100);

                entity.Property(e => e.MaNhom).HasMaxLength(200);

                entity.Property(e => e.MaSpNhaMay)
                    .HasMaxLength(100)
                    .HasColumnName("MaSP_NhaMay");

                entity.Property(e => e.Mua).HasDefaultValueSql("((1))");

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Serial).ValueGeneratedOnAdd();

                entity.Property(e => e.TenSp)
                    .IsRequired()
                    .HasColumnName("TenSP");

                entity.Property(e => e.TenSp2)
                    .HasMaxLength(150)
                    .HasColumnName("TenSP_2");

                entity.Property(e => e.TenSpNhaMay)
                    .HasMaxLength(200)
                    .HasColumnName("TenSP_NhaMay");

                entity.Property(e => e.UserInsert).HasMaxLength(100);

                entity.HasOne(d => d.KhachHangNavigation)
                    .WithMany(p => p.SanPham)
                    .HasForeignKey(d => d.KhachHang)
                    .HasConstraintName("FK_SP_KH");
            });

            modelBuilder.Entity<SanPhamChiTiet>(entity =>
            {
                entity.HasKey(e => e.MaChiTiet);

                entity.ToTable("SanPham_ChiTiet");

                entity.Property(e => e.MaChiTiet).HasMaxLength(100);

                entity.Property(e => e.CdaiCd).HasColumnName("CDaiCD");

                entity.Property(e => e.CdaiSc).HasColumnName("CDaiSC");

                entity.Property(e => e.CdaiTc).HasColumnName("CDaiTC");

                entity.Property(e => e.CdayCd).HasColumnName("CDayCD");

                entity.Property(e => e.CdaySc).HasColumnName("CDaySC");

                entity.Property(e => e.CdayTc).HasColumnName("CDayTC");

                entity.Property(e => e.CrongCd).HasColumnName("CRongCD");

                entity.Property(e => e.CrongSc).HasColumnName("CRongSC");

                entity.Property(e => e.CrongTc).HasColumnName("CRongTC");

                entity.Property(e => e.Ghep).HasMaxLength(100);

                entity.Property(e => e.GhiChu).HasMaxLength(200);

                entity.Property(e => e.KhoiLuongSc).HasColumnName("KhoiLuongSC");

                entity.Property(e => e.KhoiLuongTc).HasColumnName("KhoiLuongTC");

                entity.Property(e => e.LoaiGo).HasMaxLength(100);

                entity.Property(e => e.Long).HasMaxLength(100);

                entity.Property(e => e.MaSp)
                    .HasMaxLength(100)
                    .HasColumnName("MaSP");

                entity.Property(e => e.Mong).HasMaxLength(100);

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.NguonGoc).HasMaxLength(100);

                entity.Property(e => e.Serial).ValueGeneratedOnAdd();

                entity.Property(e => e.Slct).HasColumnName("SLCT");

                entity.Property(e => e.SxquanhTc).HasColumnName("SXquanhTC");

                entity.Property(e => e.TenChiTiet)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.TenChiTietEng).HasMaxLength(200);

                entity.Property(e => e.TenChiTietFull).HasMaxLength(500);

                entity.Property(e => e.TieuChuan).HasMaxLength(100);

                entity.Property(e => e.UserInsert).HasMaxLength(100);

                entity.HasOne(d => d.MaSpNavigation)
                    .WithMany(p => p.SanPhamChiTiet)
                    .HasForeignKey(d => d.MaSp)
                    .HasConstraintName("FK_SP_CT");
            });

            modelBuilder.Entity<SanPhamPhanHe>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("SanPham_PhanHe");

                entity.Property(e => e.CdaiSc).HasColumnName("CDaiSC");

                entity.Property(e => e.CdaiShow).HasColumnName("CDaiShow");

                entity.Property(e => e.CdaiTc).HasColumnName("CDaiTC");

                entity.Property(e => e.CdaySc).HasColumnName("CDaySC");

                entity.Property(e => e.CdayShow).HasColumnName("CDayShow");

                entity.Property(e => e.CdayTc).HasColumnName("CDayTC");

                entity.Property(e => e.CrongSc).HasColumnName("CRongSC");

                entity.Property(e => e.CrongShow).HasColumnName("CRongShow");

                entity.Property(e => e.CrongTc).HasColumnName("CRongTC");

                entity.Property(e => e.LoaiGhep).HasMaxLength(100);

                entity.Property(e => e.LoaiGo).HasMaxLength(50);

                entity.Property(e => e.MaChiTiet)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.MaChiTietParent).HasMaxLength(100);

                entity.Property(e => e.MaSp)
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnName("MaSP");

                entity.Property(e => e.NgayInsert)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.NguyenNhanThayDoi).HasMaxLength(2000);

                entity.Property(e => e.Nhom).HasMaxLength(100);

                entity.Property(e => e.SauThayDoi).HasMaxLength(2000);

                entity.Property(e => e.Slct).HasColumnName("SLCT");

                entity.Property(e => e.SoKhoiSc).HasColumnName("SoKhoiSC");

                entity.Property(e => e.SoKhoiTc).HasColumnName("SoKhoiTC");

                entity.Property(e => e.StraiKeo).HasColumnName("STraiKeo");

                entity.Property(e => e.Stt)
                    .ValueGeneratedOnAdd()
                    .HasColumnName("STT");

                entity.Property(e => e.SxquanhSc).HasColumnName("SXquanhSC");

                entity.Property(e => e.SxquanhTc).HasColumnName("SXquanhTC");

                entity.Property(e => e.TenChiTiet).HasMaxLength(100);

                entity.Property(e => e.TruocThayDoi).HasMaxLength(2000);

                entity.Property(e => e.UserDuyet).HasMaxLength(100);

                entity.Property(e => e.UserKiemTra).HasMaxLength(100);

                entity.Property(e => e.UserLap).HasMaxLength(100);

                entity.HasOne(d => d.MaSpNavigation)
                    .WithMany()
                    .HasForeignKey(d => d.MaSp)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_CTSPDM");
            });

            modelBuilder.Entity<Testabc>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("testabc");
            });

            modelBuilder.Entity<Users>(entity =>
            {
                entity.HasKey(e => e.UsersName);

                entity.Property(e => e.UsersName).HasMaxLength(100);

                entity.Property(e => e.Date)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.DateAccess).HasColumnType("datetime");

                entity.Property(e => e.Email).HasMaxLength(100);

                entity.Property(e => e.GroupUser).HasMaxLength(100);

                entity.Property(e => e.KhuVuc).HasMaxLength(50);

                entity.Property(e => e.Password).HasMaxLength(100);

                entity.Property(e => e.Stt)
                    .ValueGeneratedOnAdd()
                    .HasColumnName("STT");

                entity.Property(e => e.Ten).HasMaxLength(100);

                entity.Property(e => e.TenUser).HasMaxLength(150);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}