// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class NhaCungCap
    {
        public NhaCungCap()
        {
            DonHangPiform = new HashSet<DonHangPiform>();
        }

        public int Serial { get; set; }
        public string MaNcc { get; set; }
        public string TenNcc { get; set; }
        public string MaSoThue { get; set; }
        public string DiaChi { get; set; }
        public string TinhThanh { get; set; }
        public string QuocGia { get; set; }
        public string NguoiLh { get; set; }
        public string Email { get; set; }
        public string DienThoaiBan { get; set; }
        public string DiDong { get; set; }
        public string Website { get; set; }
        public string DaiDienPl { get; set; }
        public string SoFax { get; set; }
        public string SoTk { get; set; }
        public string TenNh { get; set; }
        public string ChungChiCoC { get; set; }
        public string LoaiHinhKinhDoanh { get; set; }
        public string UserInsert { get; set; }
        public int? NoiBo { get; set; }
        public string PathImg { get; set; }
        public string TenVietTat { get; set; }

        public virtual ICollection<DonHangPiform> DonHangPiform { get; set; }
    }
}