// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class NhaCungCapFileHoSo
    {
        public int Serial { get; set; }
        public string MaNcc { get; set; }
        public string TenHoSo { get; set; }
        public string LinkFile { get; set; }
        public string DungLuong { get; set; }
        public DateTime? NgayHieuLuc { get; set; }
        public DateTime? NgayHetHan { get; set; }
        public string NguoiDuyet { get; set; }
        public DateTime? NgayInsert { get; set; }
        public string UserInsert { get; set; }
    }
}