// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class PhieuNhanDang
    {
        public int Serial { get; set; }
        public int? ChungTu { get; set; }
        public string MaCt { get; set; }
        public int? SoLuong { get; set; }
        public string Ponumber { get; set; }
        public string UserInsert { get; set; }
        public string LoaiHang { get; set; }
        public int? CheckPrint { get; set; }
        public DateTime? NgayInsert { get; set; }
    }
}