// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class SanPham
    {
        public SanPham()
        {
            ArticleNumberProduct = new HashSet<ArticleNumberProduct>();
            KhoTpNk = new HashSet<KhoTpNk>();
            SanPhamChiTiet = new HashSet<SanPhamChiTiet>();
        }

        public int Serial { get; set; }
        public string MaSp { get; set; }
        public string MaSpNhaMay { get; set; }
        public string TenSp { get; set; }
        public string TenSpNhaMay { get; set; }
        public int? Mua { get; set; }
        public string He { get; set; }
        public string KhachHang { get; set; }
        public string TenSp2 { get; set; }
        public string MaNhom { get; set; }
        public double? Equ { get; set; }
        public string UserInsert { get; set; }
        public string LoaiGo { get; set; }
        public string DienGiai { get; set; }
        public string PathImg { get; set; }
        public double? Cdai { get; set; }
        public double? Crong { get; set; }
        public double? Ccao { get; set; }
        public DateTime? NgayInsert { get; set; }

        public virtual KhachHang KhachHangNavigation { get; set; }
        public virtual ICollection<ArticleNumberProduct> ArticleNumberProduct { get; set; }
        public virtual ICollection<KhoTpNk> KhoTpNk { get; set; }
        public virtual ICollection<SanPhamChiTiet> SanPhamChiTiet { get; set; }
    }
}