// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class SanPhamChiTiet
    {
        public SanPhamChiTiet()
        {
            ChiTietKhuVuc = new HashSet<ChiTietKhuVuc>();
        }

        public int Serial { get; set; }
        public string MaSp { get; set; }
        public string MaChiTiet { get; set; }
        public string TenChiTiet { get; set; }
        public string TenChiTietFull { get; set; }
        public string TenChiTietEng { get; set; }
        public double Slct { get; set; }
        public double? CdaySc { get; set; }
        public double? CrongSc { get; set; }
        public double? CdaiSc { get; set; }
        public double? CdayTc { get; set; }
        public double? CrongTc { get; set; }
        public double? CdaiTc { get; set; }
        public double? CdayCd { get; set; }
        public double? CrongCd { get; set; }
        public double? CdaiCd { get; set; }
        public string LoaiGo { get; set; }
        public string NguonGoc { get; set; }
        public string TieuChuan { get; set; }
        public string Mong { get; set; }
        public string Ghep { get; set; }
        public string Long { get; set; }
        public string GhiChu { get; set; }
        public int? LanSuaDoi { get; set; }
        public int? Mua { get; set; }
        public double? KhoiLuongPhoi { get; set; }
        public double? KhoiLuongTc { get; set; }
        public double? KhoiLuongSc { get; set; }
        public double? SxquanhTc { get; set; }
        public string UserInsert { get; set; }
        public DateTime? NgayInsert { get; set; }

        public virtual SanPham MaSpNavigation { get; set; }
        public virtual ICollection<ChiTietKhuVuc> ChiTietKhuVuc { get; set; }
    }
}