// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class SanPhamPhanHe
    {
        public int Stt { get; set; }
        public string MaSp { get; set; }
        public string MaChiTiet { get; set; }
        public string MaChiTietParent { get; set; }
        public string TenChiTiet { get; set; }
        public double Slct { get; set; }
        public double? CdayTc { get; set; }
        public double? CrongTc { get; set; }
        public double? CdaiTc { get; set; }
        public double? CdaySc { get; set; }
        public double? CrongSc { get; set; }
        public double? CdaiSc { get; set; }
        public double? CdayShow { get; set; }
        public double? CrongShow { get; set; }
        public double? CdaiShow { get; set; }
        public string LoaiGo { get; set; }
        public double? SoKhoiSc { get; set; }
        public double? SoKhoiTc { get; set; }
        public double? SxquanhSc { get; set; }
        public double? SxquanhTc { get; set; }
        public double? StraiKeo { get; set; }
        public string LoaiGhep { get; set; }
        public int? LanSuaDoi { get; set; }
        public string UserLap { get; set; }
        public string UserKiemTra { get; set; }
        public string UserDuyet { get; set; }
        public string TruocThayDoi { get; set; }
        public string SauThayDoi { get; set; }
        public string NguyenNhanThayDoi { get; set; }
        public string Nhom { get; set; }
        public DateTime? NgayInsert { get; set; }

        public virtual SanPham MaSpNavigation { get; set; }
    }
}