// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIServerNFC.Model
{
    public partial class Users
    {
        public int Stt { get; set; }
        public string UsersName { get; set; }
        public string Password { get; set; }
        public string GroupUser { get; set; }
        public string KhuVuc { get; set; }
        public DateTime? DateAccess { get; set; }
        public DateTime? Date { get; set; }
        public string Email { get; set; }
        public string Ten { get; set; }
        public string TenUser { get; set; }
        public int? DuyetCap { get; set; }
        public string PathImg { get; set; }
    }
}